apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}
data:
  CONNECTION_STRING: Host={{ .Values.backend.database.name }};Port=5432;Username=user;Password=Roy-peam-virk;Database=krijji_db
  SECRET: da2e5c92c90bbb5842321924aa89e67d
  SERILOG_EMAIL_PASSWORD: glml ksol asuz vage