apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingress.issuer }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: astery227@gmail.com
    privateKeySecretRef:
      name: {{ .Values.ingress.issuer }}
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx