apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.backend.database.name }}
spec:
  storageClassName: {{ .Values.backend.database.name }}
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.backend.database.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.database.name }}
spec:
  storageClassName: {{ .Values.backend.database.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi